name: DiscordBridge
version: '${version}'
main: com.discordminecraft.bridge.BridgePlugin
api-version: '1.21'
description: Bridge plugin for Discord-Minecraft integration. Exposes HTTP API and publishes player events to Redis.
author: Oracle
softdepend:
  - BlueMap
commands:
  goto:
    description: Teleport to a Discord channel's building
    usage: /goto <channel-name>
    permission: discordbridge.goto
